backend:
  name: git-gateway
  repo: ramilshirinov/remarket-site # Bura GitHub URL-dəki adları yaz
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "products"
    label: "Məhsullar"
    folder: "content/products"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Məhsulun Adı", name: "title", widget: "string" }
      - { label: "Qiymət", name: "price", widget: "string" }
      - { label: "Şəkil", name: "image", widget: "image" }
      - { label: "Məlumat", name: "body", widget: "markdown" }
