backend:
  name: github
  repo: ramilshirinov/rf-master-sales-agency
  branch: main

media_folder: "assets/images" # Şəkillərin yüklənəcəyi yer
public_folder: "/assets/images"

collections:
  - name: "products"
    label: "Məhsullar"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Başlıq", name: "title", widget: "string" }
      - { label: "Qiymət", name: "price", widget: "string" }
      - { label: "Şəkil", name: "image", widget: "image" }
      - { label: "Mətn", name: "body", widget: "markdown" }
